version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app #maps our app directory to the docker app directory, so it can continuously rebuild
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
